name:                hdracor
version:             0.1.0.0
github:              "dracor-org/hdracor"
license:             BSD3
author:              "Christian Lück"
maintainer:          "christian.lueck@rub.de"
copyright:           "2019 Christian Lück"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Social Network Analysis on Dramatic Texts with Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Type Safe Functional Drama Analysis in Haskell

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring

library:
  source-dirs: src

tests:
  hdracor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTF
    - hdracor
