name:                crawler
version:             0.1.0.0
github:              "dracor-org/hdracor"
license:             BSD3
author:              "Christian Lück"
maintainer:          "christian.lueck@rub.de"
copyright:           "2019 Christian Lück"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crawler#readme>

dependencies:
- base >= 4.7 && < 5
- hdracor
- http-conduit
- conduit
- resourcet
- bytestring
- text
- optparse-applicative

executables:
  crawldracor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  crawler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
